version: '3.5'
services:
  nuxt3:
    build: 
      context: .
      dockerfile: Dockerfile
    image: pengki
    container_name: nuxt3
    networks:
      - app-network
networks:
  app-network:
    name: efo_networks
    driver: bridge